# Numpy套件

In [1]:
a=[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## numpy套件的ndarray型態，提供element-eise的操作

In [3]:
import numpy as np
b=np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [4]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [7]:
print(np.zeros(6)) #產生6個元素均為0的一維array
print(np.zeros((3,6))) #產生18個元素均為0的二維array
print(np.zeros((2,3,6))) #產生36個元素均為0的三維array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [9]:
a=np.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4))  #改變資料的維度為4x4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


## ndarray的進階操作

In [10]:
print(np.arange(11)) #產生一個0~10的一維陣列

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #0,1,2,3,4位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [13]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(6,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[array([0, 1, 2, 3, 4]) array([6, 7, 8, 9])]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 二維ndarray取值

In [2]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:]) #第0列的元素
print(my_2d_array[1,]) #第1列的元素
print(my_2d_array[:,0]) #第0欄的元素
print(my_2d_array[1,1]) #第2列第2欄的元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


### 假設有六個組別"Modern Web","devOps","Cloud","Big Data","Security","自我挑戰組"

### 其三家人數分別為56,8,19,14,6,71人

In [6]:
import numpy as np
groups=["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman=[56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


### 請問大於10人的組別有哪些?

In [7]:
#用人數去篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']


# 除了自我挑戰組之外的組別,人數為何?

In [8]:
#用組別去篩選人數
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


### ndarry空值nan無限大inf

In [9]:
nan_array=np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


### 生成10組標準常態分配(平均為0,標準差為1的常態分派)隨機變數

In [10]:
normal_samples=np.random.normal(size=10)
print(normal_samples)

[-0.18574423 -2.86677905 -0.51117602 -0.89493988  0.3864321  -1.0091815
 -0.50980924 -0.29969157  0.2318723   0.88479277]


### 生成10組介於0~1之間的隨機變數

In [11]:
uniform_samples=np.random.uniform(size=10)
print(uniform_samples)

[0.94648827 0.39175557 0.61290328 0.79031264 0.17906811 0.45932367
 0.32871005 0.42778083 0.62397871 0.02605893]
